DROP DATABASE IF EXISTS test_db;
CREATE DATABASE test_db;
USE test_db;

CREATE TABLE IF NOT EXISTS user_colors (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  result_color VARCHAR(15),
  PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS q_group_1 (
  letterA VARCHAR(1) NOT NULL,
  A1 VARCHAR(15) NOT NULL,
  A2 VARCHAR(15) NOT NULL,
  A3 VARCHAR(15) NOT NULL,
  letterB VARCHAR(1) NOT NULL,
  B1 VARCHAR(15) NOT NULL,
  B2 VARCHAR(15) NOT NULL,
  B3 VARCHAR(15) NOT NULL,
  letterC VARCHAR(1) NOT NULL,
  C1 VARCHAR(15) NOT NULL,
  C2 VARCHAR(15) NOT NULL,
  C3 VARCHAR(15) NOT NULL,
  letterD VARCHAR(1) NOT NULL,
  D1 VARCHAR(15) NOT NULL,
  D2 VARCHAR(15) NOT NULL,
  D3 VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS q_group_2 (
  letterE VARCHAR(1) NOT NULL,
  E1 VARCHAR(15) NOT NULL,
  E2 VARCHAR(15) NOT NULL,
  E3 VARCHAR(15) NOT NULL,
  letterF VARCHAR(1) NOT NULL,
  F1 VARCHAR(15) NOT NULL,
  F2 VARCHAR(15) NOT NULL,
  F3 VARCHAR(15) NOT NULL,
  letterG VARCHAR(1) NOT NULL,
  G1 VARCHAR(15) NOT NULL,
  G2 VARCHAR(15) NOT NULL,
  G3 VARCHAR(15) NOT NULL,
  letterH VARCHAR(1) NOT NULL,
  H1 VARCHAR(15) NOT NULL,
  H2 VARCHAR(15) NOT NULL,
  H3 VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS q_group_3 (
  letterI VARCHAR(1) NOT NULL,
  I1 VARCHAR(15) NOT NULL,
  I2 VARCHAR(15) NOT NULL,
  I3 VARCHAR(15) NOT NULL,
  letterJ VARCHAR(1) NOT NULL,
  J1 VARCHAR(15) NOT NULL,
  J2 VARCHAR(15) NOT NULL,
  J3 VARCHAR(15) NOT NULL,
  letterK VARCHAR(1) NOT NULL,
  K1 VARCHAR(15) NOT NULL,
  K2 VARCHAR(15) NOT NULL,
  K3 VARCHAR(15) NOT NULL,
  letterL VARCHAR(1) NOT NULL,
  L1 VARCHAR(15) NOT NULL,
  L2 VARCHAR(15) NOT NULL,
  L3 VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS q_group_4 (
  letterM VARCHAR(1) NOT NULL,
  M1 VARCHAR(15) NOT NULL,
  M2 VARCHAR(15) NOT NULL,
  M3 VARCHAR(15) NOT NULL,
  letterN VARCHAR(1) NOT NULL,
  N1 VARCHAR(15) NOT NULL,
  N2 VARCHAR(15) NOT NULL,
  N3 VARCHAR(15) NOT NULL,
  letterO VARCHAR(1) NOT NULL,
  O1 VARCHAR(15) NOT NULL,
  O2 VARCHAR(15) NOT NULL,
  O3 VARCHAR(15) NOT NULL,
  letterP VARCHAR(1) NOT NULL,
  P1 VARCHAR(15) NOT NULL,
  P2 VARCHAR(15) NOT NULL,
  P3 VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS q_group_5 (
  letterQ VARCHAR(1) NOT NULL,
  Q1 VARCHAR(15) NOT NULL,
  Q2 VARCHAR(15) NOT NULL,
  Q3 VARCHAR(15) NOT NULL,
  letterR VARCHAR(1) NOT NULL,
  R1 VARCHAR(15) NOT NULL,
  R2 VARCHAR(15) NOT NULL,
  R3 VARCHAR(15) NOT NULL,
  letterS VARCHAR(1) NOT NULL,
  S1 VARCHAR(15) NOT NULL,
  S2 VARCHAR(15) NOT NULL,
  S3 VARCHAR(15) NOT NULL,
  letterT VARCHAR(1) NOT NULL,
  T1 VARCHAR(15) NOT NULL,
  T2 VARCHAR(15) NOT NULL,
  T3 VARCHAR(15) NOT NULL
);
